### ISSUE TITLE
 Preset adressbook not created

### ISSUE THREAD

**Issue by madmath03** [blind-coder/rcmcarddav#239] opened 2018-09-30 15:36 UTC
Hello,

Thanks for this great plugin. It's working great with my NextCloud Contacts App.
I just have an issue with the preset address book.

In the following code, you only create the address book if `find_addressbooks` returns some existing address books, even though we are in the "_create_" section :
https://github.com/blind-coder/rcmcarddav/blob/443ec4c213db5f2a3c9279b50d476f82d011eb45/carddav.php#L239-L253

The preset address book ends up never being created.
Here is the preset config I used:
```php
$prefs['NextCloud'] = array(
	// required attributes
	'name'         =>  'NextCloud Contacts',
	// will be substituted for the roundcube username
	'username'     =>  '%u', 
	// will be substituted for the roundcube password
	'password'     =>  '%p',
	// %l will be substituted for the CardDAV username
	'url'          =>  'https://cloud.domain.com/remote.php/dav/addressbooks/users/%l/',

	'active'       =>  true,
	'readonly'     =>  false,
	'refresh_time' => '02:00:00',

	'fixed'        =>  array( 'username' ),
	'hide'        =>  false,
);

```

As a quick workaround, I moved the insert after the update of the preset with the existing address book fields:
```php
			$srvs = $discovery->find_addressbooks($preset['url'], $preset['username'], $preset['password']);

			if(is_array($srvs)) {
			foreach($srvs as $srv){
				if($srv[name]) {
					if($preset[carddav_name_only])
						$preset['name'] = $srv[name];
					else
						$preset['name'] = "$abname (" . $srv[name] . ')';
				} else {
					$preset['name'] = $abname;
				}
				$preset['url'] = $srv['href'];
			}}
			self::insert_abook($preset);
```

With this, the address book is properly created with the values of the preset, even though the username and URL are fixed but that's probably a different issue.

If that seems like a proper fix for you, I will send a PR with this.

**Comment by blind-coder** [comment] 2019-01-17 09:32
I've been going over this now, and unfortunately, there are two issues with this code:
- it would create the addressbook unconditionally, even if the user does not have an addressbook (maybe by lacking the respective LDAP group for nextcloud). I'm not sure how bad this would be, but it doesn't feel 'right'
- it would create an addressbook with an incorrect URL. In my instance of nextcloud, the URL would be https://f.q.d.n/remote.php/dav/addressbooks/users/username/contacts/ but with your change the /contacts/ would be suppressed, possibly leading to errors down the line.

I guess the proper fix would be to add /contacts/ to your preset?

**Comment by madmath03** [comment] 2019-03-28 01:32
I've been going over your answer a few times already, and I must admit I am a bit at loss...

I understand your concerns but the thing is NextCloud (and maybe carddav itself) allows you to enter a "base" URL and discover carddav address books available.

To be more specific, NextCloud automatically create a `contact` address book in carddav but you can create more if you want. So if you create a new address book in NextCloud Contacts, let's say `demo`, you will have 2 address books: `contacts` and `demo`.
You can, as you suggest, use the exact URL of the address book to retrieve it, so manually add those:
* New AB `https://cloud.domain.com/remote.php/dav/addressbooks/users/%l/contacts`
* New AB `https://cloud.domain.com/remote.php/dav/addressbooks/users/%l/demo`

But you can also just enter the base URL and your great plugin will discover all the available carddav addressbook automatically:
* New AB `https://cloud.domain.com/remote.php/dav/addressbooks/users/%l/`
    * Discovers `https://cloud.domain.com/remote.php/dav/addressbooks/users/%l/contacts`
    * Discovers `https://cloud.domain.com/remote.php/dav/addressbooks/users/%l/demo`

Since this behavior happens when you **manually** add carddav address books, I expected it to work as well for automatic presets address books but it did not.

That's why I tried to see how to "fix" it and it seemed to work with the change I proposed, but I agree it's quite dirty 😅 

I guess the real issue is not _when_ you create the presets but rather how you parse the service to create presets.

I did not see (yet) what was the difference between the presets discovery with the manual discovery though...

I hope my issue is a bit more clear now.

**Comment by sphakka** [comment] 2020-06-12 09:37
Is this still valid? Indeed with (Debian 10) Roundcube-1.4.5 + carddav-3.0.3 and Nextclud-18.0.6, the default NC addressbook ('Contacts') is correctly discovered and added :-)

**Comment by mstilkerich** [comment] 2020-07-20 20:55
@madmath03 Sorry you did not get a reply. Are you still interested in the issue? The presets should use the same discovery as the manually added addressbooks. If you want, please try the v4 branch. If it doesn't work, let me know and I'll look into it.

**Comment by madmath03** [comment] 2020-07-21 11:56
I definitely wish this issue to be fixed. The plugin is pretty cool and I would love to use it "_automatically_" with NextCloud :smiley:

I do not know when I will find the time to test though... bu will let you know as soon as I can.

**Comment by mstilkerich** [comment] 2020-07-26 21:54
I believe this index was caused by a wrong unique constraint in the MySQL schema that did not allow more than one addressbook per preset. It is fixed by commit ed36d7a1aad3f756149904b6a5101e80a14cbe3d. If you find the issue persists, please comment / reopen the issue.

**Closed by mstilkerich** 2020-07-26 21:54 UTC
Labels: bug

**Comment by pgnd** [comment] 2020-09-23 04:06
@mstilkerich 

> Sorry you did not get a reply. Are you still interested in the issue? The presets should use the same discovery as the manually added addressbooks. If you want, please try the v4 branch. If it doesn't work, let me know and I'll look into it.

not sure whether to add here, @ #302, or open new issue ...

so, TL:DR 1st -- I've setup Roundcube + 
```
composer show | grep carddav
 mstilkerich/carddavclient            v0.1.6             CardDAV client library to discover and synchronize with CardDAV...
 roundcube/carddav                    v4.0.0             CardDAV adapter for connecting to CardDAV-enabled addressbooks
```

my RC db is sqlite3
my CardDAV backend is Radicale3

carddav with manually addeded addressbooks worsk as expected

presets are ignnored; no preset-referenced existing addressbooks are seen/added in RC.

what additional info's needed to (re)troubleshoot, and where to continue the discussion?

**Comment by mstilkerich** [comment] 2020-09-23 06:41
Hello,

please open a new issue, set the loglevel to debug in config.inc.php 
```
$prefs['_GLOBAL']['loglevel'] = \Psr\Log\LogLevel::DEBUG;
```
and provide:
- config.inc.php
- carddav.log

If you see that the discovery starts but fails during server communication in carddav.log, you may also set the HTTP loglevel to debug and provide carddav_http.log as well, though it should work if adding the same addressbooks manually works fine.
```
$prefs['_GLOBAL']['loglevel_http'] = \Psr\Log\LogLevel::DEBUG;
```
