### ISSUE TITLE
mysql: DB Error: Duplicate entry

### ISSUE THREAD

**Issue by 532910** [blind-coder/rcmcarddav#276] opened 2019-11-14 12:13 UTC
With mysql db the only one cardbook is autoconfigured.

carddav's config.inc.php:
```
$prefs['of'] = array(
	'name'           => 'name',
	'username'       => '%u',
	'password'       => '%p',
	'url'            => 'davserver.tld',
	'active'         => true,
	'readonly'       => false,
	'refresh_time'   => '00:01:00',
	'use_categories' => true,
	'hide'           => true,
);
```

roundcube 1.4, rcmcarddav branch: issue_259

With sqlite all works fine.

**Comment by 532910** [comment] 2019-11-14 12:23
```
DB Error: [1062] Duplicate entry '1-name' for key 'user_id' (SQL Query: INSERT INTO carddav_addressbooks(name,username,password,url,user_id,active,presetname,use_categories,refresh_time) VALUES ('name (services)','%u','{BASE64}JXA=','https://dav.davserver.tld:443/sergio%40davserver.tld/services/','1','1','name','1','00:01:00')) in /srv/www/roundcubemail-1.4.0/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login&_action=login)
DB Error: [1062] Duplicate entry '1-name' for key 'user_id' (SQL Query: INSERT INTO carddav_addressbooks(name,username,password,url,user_id,active,presetname,use_categories,refresh_time) VALUES ('name (maillists)','%u','{BASE64}JXA=','https://dav.davserver.tld:443/sergio%40davserver.tld/maillists/','1','1','name','1','00:01:00')) in /srv/www/roundcubemail-1.4.0/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login&_action=login)
DB Error: [1062] Duplicate entry '1-name' for key 'user_id' (SQL Query: INSERT INTO carddav_addressbooks(name,username,password,url,user_id,active,presetname,use_categories,refresh_time) VALUES ('name (people)','%u','{BASE64}JXA=','https://dav.davserver.tld:443/sergio%40davserver.tld/people/','1','1','name','1','00:01:00')) in /srv/www/roundcubemail-1.4.0/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login&_action=login)
DB Error: [1062] Duplicate entry '1-name' for key 'user_id' (SQL Query: INSERT INTO carddav_addressbooks(name,username,password,url,user_id,active,presetname,use_categories,refresh_time) VALUES ('name (addressbook)','%u','{BASE64}JXA=','https://dav.davserver.tld:443/sergio%40davserver.tld/addressbook/','1','1','name','1','00:01:00')) in /srv/www/roundcubemail-1.4.0/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login&_action=login)
```

**Comment by mstilkerich** [comment] 2020-07-20 20:49
What do you do to cause this problem? Please try if the problem also exists on the v4 branch. The SQL statement from the log you posted looks fine to me. I'm also using MySQL and have never seen this error.

**Comment by cnmicha** [comment] 2020-07-26 12:37
Same issue here, the error occurs when adding a new carddav address book in my case

**Comment by mstilkerich** [comment] 2020-07-26 12:47
@cnmicha: Does this happen with the current git master?

**Comment by cnmicha** [comment] 2020-07-26 15:58
I'm using v4.0.0-alpha1

**Comment by cnmicha** [comment] 2020-07-26 16:16
Happens with the latest master (23b56f3) as well.

Logfile:
> Database::insert (INSERT INTO carddav_addressbooks(name,username,password,url,user_id,active,presetname,use_categories,refresh_time) VALUES (?,?,?,?,?,?,?,?,?)) ERROR: [1062] Duplicate entry '1-' for key 'user_id'

**Comment by cnmicha** [comment] 2020-07-26 16:20
After updating the plugin to the latest version, I dropped all database tables starting with `rcmcarddav_`, signed out of Roundcube and back in. Maybe that have caused the issue?

After adding an addressbook using the plugin, I only see a blank page trying to open the Roundcube addressbook.

Logfile:
> Database::get (SELECT typename,subtype FROM carddav_xsubtypes WHERE `abook_id` = '7') ERROR: [1146] Table 'bhbnetworks_roundcube.carddav_xsubtypes' doesn't exist

**Comment by mstilkerich** [comment] 2020-07-26 21:56
I believe this index was caused by a wrong unique constraint in the MySQL schema that did not allow more than one addressbook per preset. It is fixed by commit ed36d7a1aad3f756149904b6a5101e80a14cbe3d. If you find the issue persists, please comment / reopen the issue.

**Comment by cnmicha** [comment] 2020-07-26 22:23
The issue persists on commit ed36d7a. I deleted and re-added the addressbook. Same database error as before.

**Comment by mstilkerich** [comment] 2020-07-27 04:14
It should fix the error: Duplicate entry '1-' for key 'user_id'

The last one you posted concerns a missing database table. This table like all others of rcmcarddav is created by the 0000 migration. Can you check that the DB contains this table? If not, please drop all carddav_* tables, log in to roundcube again and check that they have been created.

The carddav_migrations table should contain all the migrations from 0000 through 0008.

**Comment by mstilkerich** [comment] 2020-07-27 04:16
Btw for the commit to take effect you need to logout / login yo roundcube because only then the DB migrations are executed. (In case you still see the first error)

**Comment by cnmicha** [comment] 2020-07-27 22:01
No carddav_* tables exist. When logging in, the user sees a white page.

> Database::get (SELECT * FROM carddav_addressbooks WHERE `user_id` = '1') ERROR: [1146] Table 'roundcube.carddav_addressbooks' doesn't exist

No tables are created.

**Comment by mstilkerich** [comment] 2020-07-28 20:07
I can only reproduce this if I drop the tables while logged into roundcube and then continue making requests in roundcube. It's really needed to log out of roundcube (closing browser window is not enough, you need to use the logout button), and log in again to have the database migration scripts executed.

Nevertheless, there should not be a white page. I have changed the code to catch exceptions in all functions of the plugin that are called by roundcube to avoid this.

**Comment by cnmicha** [comment] 2020-07-28 20:40
I checked out the current master (a315ba61d6b377e657ff062ead64a44d561d5b39)

I logged out of roundcube, closed the tab, cleared all cookies, logged in and saw the following message:
![image](https://user-images.githubusercontent.com/10116544/88718799-95c48900-d122-11ea-9120-870d2bfb9773.png)

Log:
> [...] Database::get (SELECT * FROM carddav_addressbooks WHERE `user_id` = '1') ERROR: [1146] Table 'roundcube.carddav_addressbooks' doesn't exist 
> [...] Could not init rcmcarddav: [1146] Table 'roundcube.carddav_addressbooks' doesn't exist

EDIT: Deactivating the twofactor_gauthenticator plugin turns out to be a workaround. Seems as if there are strange side-effects...

**Comment by mstilkerich** [comment] 2020-07-29 04:19
Sounds like issue #175.

**Closed by mstilkerich** 2020-07-29 04:19 UTC
Labels: bug
