### ISSUE TITLE
Autocompletion in Roundcube not working against LDAP

### ISSUE THREAD

**Issue by silvereye** [blind-coder/rcmcarddav#299] opened 2020-08-19 10:49 UTC
The plugin is working fine but enabling the same causing issue in auto-completion against LDAP.

**Comment by mstilkerich** [comment] 2020-08-19 11:49
Hello, could you be a bit more specific about the kind of issue you are experiencing?

**Comment by silvereye** [comment] 2020-08-19 12:19
> Hello, could you be a bit more specific about the kind of issue you are experiencing?
> 
> Which version of the plugin are you using?

We are using the latest Roundcube Webmail 1.4.8 along with plugin "roundcube/carddav": "^v4.0.0-alpha1". I am able to sync my contacts but when we compose any mail than autocompletion feature doesn't work against LDAP address book while working with CardDAV address book, disabling the plugin fixes my issues.

**Comment by mstilkerich** [comment] 2020-08-19 15:11
What is your setting for autocomplete_addressbooks in the roundcube configuration? What does your LDAP config look like?

I'm not sure whether I can help here. I don't have LDAP to test with, and I don't know how roundcube's LDAP integration is designed. Maybe it's even intended behavior that LDAP search is only used when there are no other address sources. The plugin registers its addressbook as autocompletion sources exactly as shown by the example addressbook plugin that ships with roundcube, and autocompletion with the normal roundcube addressbook works in parallel with carddav addressbooks.

I'll try to help, but you may be better of checking with the roundcube developers whether LDAP autocompletion should work in parallel to other addressbooks (btw, does completion of the roundcube contacts work in parallel with LDAP?)

**Comment by silvereye** [comment] 2020-08-20 04:23
> What is your setting for autocomplete_addressbooks in the roundcube configuration? What does your LDAP config look like?
> 
> I'm not sure whether I can help here. I don't have LDAP to test with, and I don't know how roundcube's LDAP integration is designed. Maybe it's even intended behavior that LDAP search is only used when there are no other address sources. The plugin registers its addressbook as autocompletion sources exactly as shown by the example addressbook plugin that ships with roundcube, and autocompletion with the normal roundcube addressbook works in parallel with carddav addressbooks.
> 
> I'll try to help, but you may be better of checking with the roundcube developers whether LDAP autocompletion should work in parallel to other addressbooks (btw, does completion of the roundcube contacts work in parallel with LDAP?)

What is your setting for autocomplete_addressbooks in the roundcube configuration? What does your LDAP config look like?
Response - $config['autocomplete_addressbooks'] = array('sql','ldapglobal');

does completion of the roundcube contacts work in parallel with LDAP?

Response - Yes

**Comment by mstilkerich** [comment] 2020-08-20 07:27
Hello,

  you are right, it was already fixed with a315ba61d6b377e657ff062ead64a44d561d5b39.

Please use the current dev-master, which contains other bug fixes as well.

**Comment by silvereye** [comment] 2020-08-20 07:44
> Hello,
> 
> you are right, it was already fixed with [a315ba6](https://github.com/blind-coder/rcmcarddav/commit/a315ba61d6b377e657ff062ead64a44d561d5b39).
> 
> Please use the current dev-master, which contains other bug fixes as well.

Upgrading to dev-master fixed my issues, Thanks a lot

**Closed** 2020-08-20 07:46 UTC
