### ISSUE TITLE
:XML(): Empty string supplied as input when trying to sync changes from the WebDAV server

### ISSUE THREAD

**Issue by djan91** [blind-coder/rcmcarddav#209] opened 2017-10-15 21:25 UTC
When trying to sync changes from WebDAV Server (sabre.io) the following happens:

> [15-Oct-2017 16:52:39 +0200]: <86mg1mqe> BACKEND: (cdfopen) list_records_sync_collection requesting https://localhost:443/dav/addressbooks/example/Contacts/ as user example [RL 5]
> [15-Oct-2017 16:52:39 +0200]: <86mg1mqe> BACKEND: (cdfopen) Code: 500
> [15-Oct-2017 16:52:39 +0200]: <86mg1mqe> BACKEND: (cdfopen) success: array (
>   'status' => 500,
>   'headers' => 
>   Httpful\Response\Headers::__set_state(array(
>      'headers' => 
>     array (
>       'server' => 'nginx',
>       'date' => 'Sun, 15 Oct 2017 14:52:39 GMT',
>       'content-type' => 'application/xml; charset=utf-8',
>       'transfer-encoding' => 'chunked',
>       'connection' => 'keep-alive',
>       'cache-control' => 'max-age=2592000',
>       'expires' => 'Tue, 14 Nov 2017 14:52:39 GMT',
>       'x-robots-tag' => 'noindex, nofollow',
>       'x-powered-by' => 'PHP/7.0.14',
>       'x-sabre-version' => '3.2.2',
>       'x-varnish-cache' => 'YES',
>     ),
>   )),
>   'body' => '<?xml version="1.0" encoding="utf-8"?>
> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>   <s:sabredav-version>3.2.2</s:sabredav-version>
>   <s:exception>ErrorException</s:exception>
>   <s:message>XMLReader::XML(): Empty string supplied as input</s:message>
> </d:error>
> ',
> )

> [15-Oct-2017 16:21:08 +0200]: <86mg1mqe> BACKEND: (cdfopen) query_addressbook_multiget requesting https://localhost:443/dav/addressbooks/example/Contacts/ as user example [RL 5]
> [15-Oct-2017 16:21:08 +0200]: <86mg1mqe> BACKEND: (cdfopen) Code: 500
> [15-Oct-2017 16:21:08 +0200]: <86mg1mqe> BACKEND: (cdfopen) success: array (
>   'status' => 500,
>   'headers' =>
>   Httpful\Response\Headers::__set_state(array(
>      'headers' =>
>     array (
>       'server' => 'nginx',
>       'date' => 'Sun, 15 Oct 2017 14:21:08 GMT',
>       'content-type' => 'application/xml; charset=utf-8',
>       'transfer-encoding' => 'chunked',
>       'connection' => 'keep-alive',
>       'cache-control' => 'max-age=2592000',
>       'expires' => 'Tue, 14 Nov 2017 14:21:08 GMT',
>       'x-robots-tag' => 'noindex, nofollow',
>       'x-powered-by' => 'PHP/7.0.14',
>       'x-sabre-version' => '3.2.2',
>       'x-varnish-cache' => 'YES',
>     ),
>   )),
>   'body' => '<?xml version="1.0" encoding="utf-8"?>
> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>   <s:sabredav-version>3.2.2</s:sabredav-version>
>   <s:exception>ErrorException</s:exception>
>   <s:message>XMLReader::XML(): Empty string supplied as input</s:message>
> </d:error>
> ',
> )
> [15-Oct-2017 16:21:08 +0200]: <86mg1mqe> An error (status 500) occured while retrieving vcards for addressbook 9. Synchronization aborted.
> [15-Oct-2017 16:21:08 +0200]: <86mg1mqe> BACKEND: (refreshdb_from_server) server refresh took 0 seconds

The "XMLReader::XML(): Empty string supplied as input" error occurs.

What's more - syncing between Android phones using DAVdroid works flawlessly and the issue appears only when CardDAV (rcmcarddav) tries to sync changes from the server. When it comes to push changes to WebDAV server - everything works OK and DAVdroid sync changes without any problems.

**Comment by dioobr** [comment] 2019-01-27 21:50
I'm having the same problem.

SabreDAV 3.2.3 / Roundcube 1.4 beta / PHP 7.1.26 / NGINX 1.14.2

**Comment by intelli-xlcode** [comment] 2020-01-29 06:53
Same problem here.

Roundcube Carddav 3.0.3 / Baikal 0.5.3 / Roundcube 1.4.1 / PHP 7.2.27 / Apache 2.4.41

**Comment by intelli-xlcode** [comment] 2020-01-30 07:48
This seems to be a curl related problem.
Inspired by [this](https://github.com/agendav/agendav/issues/191#issuecomment-270563580) thread, I've replaced CURLAUTH_DIGEST with CURLAUTH_ANY in carddav/vendor/nategood/httpful/src/Httpful/Request.php and everything seems to be working normally.

```diff
--- carddav/vendor/nategood/httpful/src/Httpful/Request.php.orig    2020-01-30 09:16:48.863085000 +0200
+++ carddav/vendor/nategood/httpful/src/Httpful/Request.php 2020-01-30 09:17:11.114970000 +0200
@@ -147,7 +147,7 @@
      */
     public function hasDigestAuth()
     {
-        return isset($this->password) && isset($this->username) && $this->additional_curl_opts[CURLOPT_HTTPAUTH] == CURLAUTH_DIGEST;
+        return isset($this->password) && isset($this->username) && $this->additional_curl_opts[CURLOPT_HTTPAUTH] == CURLAUTH_ANY;
     }

     /**
@@ -268,7 +268,7 @@
      */
     public function digestAuth($username, $password)
     {
-        $this->addOnCurlOption(CURLOPT_HTTPAUTH, CURLAUTH_DIGEST);
+        $this->addOnCurlOption(CURLOPT_HTTPAUTH, CURLAUTH_ANY);
         return $this->basicAuth($username, $password);
     }
```

**Comment by mstilkerich** [comment] 2020-07-22 20:24
Closing this as duplicate of #188

**Closed by mstilkerich** 2020-07-22 20:24 UTC
Labels: duplicate
