### ISSUE TITLE
With sqlite: DB Error: [1] no such table 

### ISSUE THREAD

**Issue by realriot** [blind-coder/rcmcarddav#96] opened 2015-04-14 18:24 UTC
I'm using roundcube with sqlite as db backend. After installing carddav I see lots of db failures within the error log:

no such table: carddav_contacts ...

Seems that the tables were not created during plugin initialization. How can I do that afterwards? Or do I have to configure something else?

**Comment by blind-coder** [comment] 2015-04-15 06:26
This will probably be resolved once #95 is fixed.

**Comment by realriot** [comment] 2015-04-15 13:31
Since #95 didn't have an impact an this i'M getting the following errors on every login (errors log)

I'm using SQLITE3

[15-Apr-2015 15:27:06 +0200]: <0dj74956> DB Error: [1] no such table: carddav_migrations (SQL Query: SELECT * FROM carddav_migrations WHERE filename IN ('0000-dbinit','0000-sample')) in /Library/Server/Web/Data/Sites/mail.mydomain.de/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login?_task=login&_action=login)
[15-Apr-2015 15:27:06 +0200]: <0dj74956> DB Error: [1] table carddav_addressbooks already exists (SQL Query: -- table to store the configured address books
CREATE TABLE carddav_addressbooks (
        id           integer NOT NULL PRIMARY KEY,
        name         VARCHAR(64) NOT NULL,
        username     VARCHAR(64) NOT NULL,
        password     VARCHAR(255) NOT NULL,
        url          VARCHAR(255) NOT NULL,
        active       TINYINT UNSIGNED NOT NULL DEFAULT 1,
        user_id      integer NOT NULL,
        last_updated DATETIME NOT NULL DEFAULT 0,  -- time stamp of the last update of the local database
        refresh_time TIME NOT NULL DEFAULT '01:00:00', -- time span after that the local database will be refreshed
        sync_token   VARCHAR(255) NOT NULL DEFAULT '', -- sync-token the server sent us for the last sync
        authentication_scheme VARCHAR(64) NOT NULL DEFAULT "auto", -- the HTTP authentication scheme to use, auto will be overwritten

        presetname   VARCHAR(64),                  -- presetname

        -- not enforced by sqlite < 3.6.19
        FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE carddav_contacts (
        id           integer NOT NULL PRIMARY KEY,
        abook_id     integer NOT NULL,
        name         VARCHAR(255) NOT NULL, -- display name
        email        VARCHAR(255),          -- ", " separated list of mail addresses
        firstname    VARCHAR(255),
        surname      VARCHAR(255),
        organization VARCHAR(255),
        showas       VARCHAR(32) NOT NULL DEFAULT '', -- special display type (e.g., as a company)
        vcard        TEXT NOT NULL,         -- complete vcard
        etag         VARCHAR(255) NOT NULL, -- entity tag, can be used to check if card changed on server
        uri          VARCHAR(255) NOT NULL, -- path of the card on the server
        cuid         VARCHAR(255) NOT NULL, -- unique identifier of the card within the collection

        UNIQUE(uri,abook_id),
        UNIQUE(cuid,abook_id),

        -- not enforced by sqlite < 3.6.19
        FOREIGN KEY(abook_id) REFERENCES carddav_addressbooks(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX carddav_contacts_abook_id_idx ON carddav_contacts(abook_id);

CREATE TABLE carddav_xsubtypes (
        id       integer NOT NULL PRIMARY KEY,
        typename VARCHAR(128) NOT NULL,  -- name of the type
        subtype  VARCHAR(128) NOT NULL,  -- name of the subtype
        abook_id integer NOT NULL,

        -- not enforced by sqlite < 3.6.19
        FOREIGN KEY(abook_id) REFERENCES carddav_addressbooks(id) ON DELETE CASCADE ON UPDATE CASCADE,
        UNIQUE(typename,subtype,abook_id)
);


CREATE TABLE carddav_groups (
        id       integer NOT NULL PRIMARY KEY,
        abook_id integer NOT NULL,
        name VARCHAR(255) NOT NULL, -- display name
        vcard TEXT NOT NULL,        -- complete vcard
        etag VARCHAR(255) NOT NULL, -- entity tag, can be used to check if card changed on server
        uri  VARCHAR(255) NOT NULL, -- path of the card on the server
        cuid VARCHAR(255) NOT NULL, -- unique identifier of the card within the collection

        UNIQUE(uri,abook_id),
        UNIQUE(cuid,abook_id),

        -- not enforced by sqlite < 3.6.19
        FOREIGN KEY(abook_id) REFERENCES carddav_addressbooks(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE carddav_group_user (
        group_id   integer NOT NULL,
        contact_id integer NOT NULL,

        PRIMARY KEY(group_id,contact_id),

        -- not enforced by sqlite < 3.6.19
        FOREIGN KEY(group_id) REFERENCES carddav_groups(id) ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY(contact_id) REFERENCES carddav_contacts(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE carddav_migrations (
        ID integer NOT NULL PRIMARY KEY,
        filename VARCHAR(64) NOT NULL,
        processed_at TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

        UNIQUE(filename)
)) in /Library/Server/Web/Data/Sites/mail.mydomain.de/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login?_task=login&_action=login)
[15-Apr-2015 15:27:06 +0200]: <0dj74956> DB Error: [1] no such table: carddav_migrations (SQL Query: INSERT INTO carddav_migrations (filename) VALUES ('0000-dbinit')) in /Library/Server/Web/Data/Sites/mail.mydomain.de/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login?_task=login&_action=login)
[15-Apr-2015 15:27:06 +0200]: <0dj74956> DB Error: [1] no such table: carddav_migrations (SQL Query: SELECT * FROM carddav_migrations; -- Just an example migration.) in /Library/Server/Web/Data/Sites/mail.mydomain.de/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login?_task=login&_action=login)
[15-Apr-2015 15:27:06 +0200]: <0dj74956> DB Error: [1] no such table: carddav_migrations (SQL Query: INSERT INTO carddav_migrations (filename) VALUES ('0000-sample')) in /Library/Server/Web/Data/Sites/mail.mydomain.de/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login?_task=login&_action=login)

**Comment by blind-coder** [comment] 2015-04-16 06:00
It seems the 0000-dbinit migration is not made correctly and the table carddav_migrations was not created.
Can you check the very first occurance of this error? It should contain information about why the migration did not work correctly.

Did you try to upgrade from a previous installation or is this a new installation?

**Comment by brocktice** [comment] 2015-05-24 16:48
I am seeing this on a fresh install, trying to get this going in mail-in-a-box (https://mailinabox.email).

In carddav.warn:

[24-May-2015 12:46:31 -0400]: <5vcv3al6> BACKEND: (update_addressbook) [1] no such table: carddav_addressbooks


in roundcube error log:

[24-May-2015 12:46:31 -0400]: <5vcv3al6> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT id,password FROM carddav_addressbooks WHERE user_id='1') in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /mail/?_task=login?_task=login&_action=login)
[24-May-2015 12:46:31 -0400]: <5vcv3al6> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT * FROM carddav_addressbooks WHERE user_id='1' AND presetname is not null) in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /mail/?_task=login?_task=login&_action=login)
[24-May-2015 12:46:31 -0400]: <5vcv3al6> DB Error: [1] no such table: carddav_addressbooks (SQL Query: UPDATE carddav_addressbooks SET authentication_scheme='basic' WHERE id=NULL) in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /mail/?_task=login?_task=login&_action=login)
[24-May-2015 12:46:31 America/New_York] PHP Fatal error:  Using $this when not in object context in /usr/local/lib/roundcubemail/plugins/carddav/carddav_backend.php on line 2054

Seeing if I can figure it out myself.

**Comment by blind-coder** [comment] 2015-06-02 07:56
Thanks @brocktice, that confirms my suspicion that the sqlite3.sql is not executed. I'll look into this.

**Comment by brocktice** [comment] 2015-06-07 14:41
There are no references at all to the dbinit directory, only dbmigrations. It looks like in carddav.php the migrations are supposed to be loaded. I don't really understand what's going on with the qmarks bit It seems like the problem must be between lines 60 and 81. My PHP is a bit rusty but I'm reading through it trying to figure out what's going on.

**Comment by blind-coder** [comment] 2015-06-07 14:56
Ah, yes, dbinit is something that should really go away, it's all set up with dbmigrations now.
It seems to be sqlite-specific though.

**Comment by brocktice** [comment] 2015-06-07 15:03
OK I've got what's going on with the question marks. You're just replacing them with the names of the migrations. About time to set up a vm and do some more testing, I think.

**Comment by blind-coder** [comment] 2015-06-07 15:08
Yeah, the ? are proper SQL parameter handling.

I really... hmm... what OS are you running on?

**Comment by blind-coder** [comment] 2015-06-07 15:09
Could you please run the following commands and paste me the output:
```bash
mkdir test/
touch test/a test/b test/c
php
<?php
print_r(scandir(dirname(__FILE__)."/test"));
?>
```

**Comment by blind-coder** [comment] 2015-06-07 15:13
Also, the output of this:
```bash
php
<?php
print_r(array_diff(scandir(dirname(__FILE__)."/test"), array('..', '.')));
?>
```

**Comment by brocktice** [comment] 2015-06-07 15:20
Sure, just getting it set up. This is Ubuntu 14.04 on x86_64, the required platform for mailinabox.

**Comment by brocktice** [comment] 2015-06-07 15:22
For the first:

Array
(
    [0] => .
    [1] => ..
    [2] => a
    [3] => b
    [4] => c
)

**Comment by blind-coder** [comment] 2015-06-07 15:26
Looks right, it _should_ be picking up the sqlite dbinit migration.
Is there anything about "Unknown database backend" in the carddav log?

**Comment by brocktice** [comment] 2015-06-07 15:32
Brand new install, first login, getting this in carddav.warn:

[07-Jun-2015 11:30:53 -0400]: <vfeci5i0> BACKEND: (update_addressbook) [1] no such table: carddav_addressbooks

and this in errors:

[07-Jun-2015 11:30:52 -0400]: <vfeci5i0> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT id,password FROM carddav_addressbooks WHERE user_id='1') in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /mail/?_task=login?_task=login&_action=login)
[07-Jun-2015 11:30:52 -0400]: <vfeci5i0> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT * FROM carddav_addressbooks WHERE user_id='1' AND presetname is not null) in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /mail/?_task=login?_task=login&_action=login)
[07-Jun-2015 11:30:53 -0400]: <vfeci5i0> DB Error: [1] no such table: carddav_addressbooks (SQL Query: UPDATE carddav_addressbooks SET authentication_scheme='basic' WHERE id=NULL) in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /mail/?_task=login?_task=login&_action=login)
[07-Jun-2015 11:30:53 America/New_York] PHP Fatal error:  Using $this when not in object context in /usr/local/lib/roundcubemail/plugins/carddav/carddav_backend.php on line 2054

**Comment by blind-coder** [comment] 2015-06-07 15:33
Nothing about migrations? That's reeaally odd.
Did you login _after_ activating the plugin?

**Comment by blind-coder** [comment] 2015-06-07 15:34
Because the migrations are only checked via the login_after hook.

**Comment by brocktice** [comment] 2015-06-07 15:34
The way it's currently being done is everything is installed before I ever login. Does this depend on logging into roundcube once before the plugin is installed?

**Comment by brocktice** [comment] 2015-06-07 15:35
I get stuck at a white screen trying to log in for the first time.

**Comment by blind-coder** [comment] 2015-06-07 15:38
> I get stuck at a white screen trying to log in for the first time.

That might be an explanation... Something might be broken in the checkMigrations funciton.

**Comment by brocktice** [comment] 2015-06-07 15:42
And after the first attempt I can't log in unless I disable the carddav plugin:

[07-Jun-2015 11:40:43 -0400]: <vfeci5i0> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT id FROM carddav_addressbooks WHERE user_id='1' AND active=1) in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (GET /mail/)
[07-Jun-2015 11:40:43 -0400]: <vfeci5i0> DB Error: [1] no such table: carddav_addressbooks (GET /mail/)

**Comment by brocktice** [comment] 2015-06-07 15:46
I'm doing some basic printlining with the log, it doesn't appear to be getting into the checkMigrations function before it starts throwing errors.

**Comment by brocktice** [comment] 2015-06-07 15:52
Aha, swapping the order of the hooks from init_presets() then checkMigrations() to checkMigrations() followed by init_presets() seems to fix it. Going to try again fresh.

**Comment by blind-coder** [comment] 2015-06-07 15:54
> Aha, swapping the order of the hooks from init_presets() then checkMigrations() to checkMigrations() followed by init_presets() seems to fix it. Going to try again fresh.

Oh. OH. Yeah, obviously... init_presets does several SQL queries. And if the migrations didn't run by then, it woun't work...
I'll swap it around in the issue_96 branch.

**Comment by brocktice** [comment] 2015-06-07 16:37
NOW there's a problem with checkMigrations exposed. It's not correctly initializing. It's throwing errors because the carddav_migrations table doesn't exist. Investigating.

**Comment by brocktice** [comment] 2015-06-07 17:05
It appears only the first query in the sqlite3.sql file is being processed with the current code, even after the carddav_migrations table is initialized.

**Comment by blind-coder** [comment] 2015-06-07 17:16
Can you add the following after set_option('ignore_key_errors', true) and then check in roundcube/logs/sql
```php
$dbh->set_debug(true);
```

**Comment by brocktice** [comment] 2015-06-07 18:36
OK, I've got working code, but it's more complicated, involves preg_match_all. I'll stash that and try this first.

**Comment by blind-coder** [comment] 2015-06-07 18:37
Hm, preg_match _is_ expensive, but if it's only called once per Login, I guess it'd be acceptable.

**Comment by brocktice** [comment] 2015-06-07 18:51
The query (all of the create table statements and such) shows with no errors in the roundcube sql logs, but only carddav_addressbooks is created.

**Comment by blind-coder** [comment] 2015-06-07 19:02
That's bad. It means that the sqlite backend is only executing the first statement and not the entire string.
Probably need to split it up into singular queries.

**Comment by brocktice** [comment] 2015-06-07 19:12
PR incoming.

**Comment by blind-coder** [comment] 2015-06-07 19:21
Great!
I'll be looking at it tomorrow or the day after!

**Comment by blind-coder** [comment] 2015-06-10 08:01
I have merged the PR and updated it a little bit so that it only uses dbmigrations, not dbinit so we have only one place with sql queries.
I have successfully tested it with sqlite and mysql. If you could confirm that it works, I'll merge it into master.

**Comment by blind-coder** [comment] 2015-06-11 09:03
@brocktice @realriot 
Can you check latest issue_96 branch if it works for you, too?
I'd like to close this issue and start preparing a new release then.

**Comment by brocktice** [comment] 2015-06-11 23:49
Sorry I haven't had a chance, mostly I do this stuff on weekends. I'll try to get a test run in tonight.

On June 11, 2015 3:03:03 AM MDT, Benjamin Schieder <notifications@github.com> wrote:
>@brocktice @realriot 
>Can you check latest issue_96 branch if it works for you, too?
>I'd like to close this issue and start preparing a new release then.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/96#issuecomment-111051294

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brocktice** [comment] 2015-06-12 17:04
OK just tested this with mailinabox, seems to work now. Thanks!

**Comment by brocktice** [comment] 2015-06-12 17:04
I'll watch for the merge into the new release.

**Comment by blind-coder** [comment] 2015-06-13 07:21
Awesome, thanks for the feedback!
I'll merge it into master soon then!

**Closed by blind-coder** 2015-06-13 07:21 UTC

**Comment by pbiering** [comment] 2016-12-11 12:17
Is this issue really fixed in current version? Tried a fresh installation and it won't work:

WebUI:
_DATABASE ERROR: CONNECTION FAILED!
Unable to connect to the database!
Please contact your server-administrator._

Log:

```
[11-Dec-2016 13:04:22 +0100]: <7htasdnj> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT id FROM carddav_addressbooks WHERE user_id='2' AND active=1) in /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (GET /roundcubemail/?_task=mail)
[11-Dec-2016 13:04:22 +0100]: <7htasdnj> DB Error: [1] no such table: carddav_addressbooks (GET /roundcubemail/?_task=mail)
```

Looks like on first run, the SQLlite DB is not initialized at all.

Put some log statements into the "carddav.php", looks like "login_after" hooks ("checkMigrations", "init_presets") were never executed, only the "init()" function itself and the program stops before executing the hooks.

Personally I would say there is a try-catch missing in "init()" around

```
        $dbh = rcmail::get_instance()->db;
        $sql_result = $dbh->query('SELECT id FROM ' .
                $dbh->table_name('carddav_addressbooks') .
                ' WHERE user_id=? AND active=1',
                $_SESSION['user_id']);

        while ($abookrow = $dbh->fetch_assoc($sql_result)) {
                $abookname = "carddav_" . $abookrow['id'];
                if (!in_array($abookname, $sources)) {
                        $sources[] = $abookname;
                }
        }
```

Because if db-init/migration is afer login started, such a query can fail on the very first time

Roundcubemail is btw: roundcubemail-1.1.6-1.el7.noarch

**Comment by blind-coder** [comment] 2016-12-11 13:10
That's weird, it really shouldn't be called as $_SESSION['user_id'] should not be set at this point.
I'll check this out later, but in the meantime, are you sure that $_SESSION['user_id'] is set every time init() is called? Especially before the first login?

**Comment by pbiering** [comment] 2016-12-11 13:42
I put one debug line on start on "init() (and 3 other loggings later, only one is shown)
```
    rcmail::write_log("carddav", "Init: ". $_SESSION['user_id']);
    if(!in_array($this->rc->task, $tasks))
...
        $sources = (array) $config->get('autocomplete_addressbooks', array('sql'));
        rcmail::write_log("carddav", "Init2: ");
```
and log shows on user login:
```
[11-Dec-2016 14:36:40 +0100]: <7htasdnj> Init: 
[11-Dec-2016 14:36:53 +0100]: <7htasdnj> Init: 
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init: 2
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init2: 
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init3: 
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init4: 
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init: 2
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init2: 
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init3: 
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> Init4: 
```

resulting in 4 error log lines:

```
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT id FROM carddav_addressbooks WHERE user_id='2' AND active=1) in /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /roundcubemail/?_task=mail&_action=)
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> DB Error: [1] no such table: carddav_addressbooks (POST /roundcubemail/?_task=mail&_action=)
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT id FROM carddav_addressbooks WHERE user_id='2' AND active=1) in /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (GET /roundcubemail/?_task=mail)
[11-Dec-2016 14:37:08 +0100]: <aoerfrpk> DB Error: [1] no such table: carddav_addressbooks (GET /roundcubemail/?_task=mail)
```

Just note that I have also Google 2-factor authentication plug running, perhaps this influences something

**Comment by blind-coder** [comment] 2016-12-12 08:09
I can't reproduce this here, unfortunately, not with Roundcube 1.1.x or 1.2.x, with MySQL or SQLite.

If you put that block in a try-catch block, does it "fix" the issue for you?

**Comment by pbiering** [comment] 2016-12-13 07:12
I have now created a try-catch block around the DB statements:

```
@@ -145,6 +149,7 @@
 	$sources = (array) $config->get('autocomplete_addressbooks', array('sql'));
 
 	$dbh = rcmail::get_instance()->db;
+	if (array_key_exists("carddav_addressbooks", $dbh->list_tables())) {
 	$sql_result = $dbh->query('SELECT id FROM ' .
 		$dbh->table_name('carddav_addressbooks') .
 		' WHERE user_id=? AND active=1',
@@ -155,7 +160,9 @@
 		if (!in_array($abookname, $sources)) {
 			$sources[] = $abookname;
 		}
-	}
+	}} else {
+        	rcmail::write_log("carddav", "init() skip fetching addressbook infos (missing table)");
+	};
 	$config->set('autocomplete_addressbooks', $sources);
 	$skin_path = $this->local_skin_path();
 	$this->include_stylesheet($skin_path . '/carddav.css');

```
Now I'm able to login, also the carddav settings menu is show but if I select this I get next unexpected message telling me that my PHP version is too old: 5.4.16 and it is requesting >= 5.6.18.

That's ugly, system is a CentOS Enterprise Linux 7 (latest version of a common used professional Linux server system) and there is no PHP 5.6 available for that OS.

What are the dependencies that PHP 5.4.16 can't be supported?

BTW: had already some work to solve the dependency to nategood-httpful by rebuild using following spec file: https://github.com/siwinski/rpms/blob/master/php-nategood-httpful/php-nategood-httpful.spec

**Comment by blind-coder** [comment] 2016-12-13 07:24
I can't help with the httpful building, but you can disable the PHP version check in ``config.inc.php``and see if it works. The dependency on 5.6.18 is simply the lowest version I had available to check against.

**Comment by pbiering** [comment] 2016-12-13 07:44
httpful building was already solved, so no help required. Version check adjusted, now able to configure a carddav server, but on save following occurs in log:

`[13-Dec-2016 08:40:22 Europe/Berlin] PHP Fatal error:  Using $this when not in object context in /usr/share/roundcubemail/plugins/carddav/carddav_backend.php on line 2296
`

probably caused by still missing table, as other log shows:

```
[13-Dec-2016 08:41:18 +0100]: <8qg06sc2> init() userid=2
[13-Dec-2016 08:41:18 +0100]: <8qg06sc2> init() skip fetching addressbook infos (missing table)
```

=> the carddav_addressbooks "bootstrap" by user (means inserting the required table schema) was still not executed...on which position in the code should this happen and when?

**Comment by blind-coder** [comment] 2016-12-13 07:47
This happens at login time in the function checkMigrations() in ``carddav.php``.

**Comment by pbiering** [comment] 2016-12-14 06:43
Thank you for that hint, I've investigated further by putting some log statements there and it looks like that the login-hooks are not working in case of "twofactor_gauthenticator" plugin is enabled. Temporary disabled the 2-factor auth and "checkMigrations" and "init_presets" are executed.

Now the question is why is this happen that "login_after" hooks are not executed in case of 2-factor auth is active (also registering an "login_after" hook)...perhaps a sort/sequence order issue or other hook should be used instead of "login_after".

**Comment by blind-coder** [comment] 2016-12-14 07:01
I have opened issue #175 for this to further track this.
