### ISSUE TITLE
Infinite loop if address book doesn't exists

### ISSUE THREAD

**Issue by maethor** [blind-coder/rcmcarddav#38] opened 2014-06-02 16:03 UTC
Hi,

I'm using this plugin to allow my users to access their Owncloud address book directly from Roundcube. Authentification in Roundcube and Owncloud is centralized with LDAP so can I use a preset in `config.inc.php`.

Everything works fine except one thing. If a new user try to log in Roundcube first (so his owncloud account is not created yet, and owncloud do not return an address book with carddav), the login loops until server times out.

With RCMCardDav 0.9.2 and RoundCube 1.0.0-rc1, commenting this line https://github.com/blind-coder/rcmcarddav/blob/master/carddav_common.php#L212 was making things better. Login was working every time. In RoundCube 1.0.0, this trick doesn't work anymore. So I updated RCMCardDav to 1.0.0, but the bug is still here.

The strange thing is that, sometimes, the login works… Maybe one out of five. I can't find any pattern to explain that.

This is my carddav config:

```
$prefs['Owncloud'] = array(
    'name'     => 'Cloud',
    'username' => '%u',
    'password' => '%p',
    'url'      => 'https://example.com/remote.php/carddav/addressbooks/%u/',
    'carddav_name_only' => true,

    'active'   => true,
    'readonly' => false,
    'preemptive_auth' => 1,

    'fixed' => array ('username', 'password', 'url', 'preemptive_auth', 'refresh_time'),
    'hide' => true,
);
```

What do you think ?

**Comment by mstilkerich** [comment] 2020-07-14 10:39
I'm closing this issue because of it's age. The discovery mechanism is simplified in the v4 development branch and I believe it should resolve the issue:
https://github.com/blind-coder/rcmcarddav/tree/v4

If the issue is still relevant to you, please comment / reopen on the issue.

**Closed by mstilkerich** 2020-07-14 10:39 UTC
