### ISSUE TITLE
Pop-up Error during saving contact (first time)

### ISSUE THREAD

**Issue by olistaps** [blind-coder/rcmcarddav#44] opened 2014-06-13 14:37 UTC
Hello,
Each time, when i save a contact for the first time a pop up appear with the text (An error has occurred during recording) but if i refresh... no problem the contact appear (sometimes twice or more)  and i could do modify, delete, etc... without error pop up screen (roundcube 1.0.1 - Os x server 3.2.1 (10.9.3) ) Thanks you for your help

**Comment by GO3LIN** [comment] 2015-03-02 15:12
Hello,
I am facing the same issue,

**Comment by oljask** [comment] 2016-10-07 14:09
Hi same with my instance. When I try to edit contact in OwnCloud address book, I get a pop up with error. However contact gets updated.

**Comment by mstilkerich** [comment] 2020-07-14 10:41
I'm closing this issue because of it's age. Please try the v4 development branch, which also supports creation of cards using POST if advertised by the server:
https://github.com/blind-coder/rcmcarddav/tree/v4

If the issue is still relevant to you, please comment / reopen on the issue.

**Closed by mstilkerich** 2020-07-14 10:41 UTC
