### ISSUE TITLE
errors on contacts with missing subtypes in attributes

### ISSUE THREAD

**Issue by c-schwamborn** [blind-coder/rcmcarddav#132] opened 2016-01-20 08:23 UTC
During testing I imported my own address book with thunderbird/sogo-connector to my test server. When rcmcarddav synchronizes this address book /var/log/roundcube/errors is spammed with errors like this:

[22-Nov-2015 22:22:50 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/share/roundcube/plugins/carddav/carddav_discovery.php on line 253
[22-Nov-2015 22:22:56 Europe/Berlin] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/local/share/roundcube/plugins/carddav/carddav_backend.php on line 1438
[22-Nov-2015 22:22:56 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/share/roundcube/plugins/carddav/carddav_backend.php on line 1332
[22-Nov-2015 22:22:56 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/share/roundcube/plugins/carddav/carddav_backend.php on line 1350

I wrote some if's to your plugin and it seems to work, but I don't know about the consequences as I don't know the code.

Cheers, Christian

[missing_subtype_in_vcard.patch.txt](https://github.com/blind-coder/rcmcarddav/files/97113/missing_subtype_in_vcard.patch.txt)

PS.: Little question: As you can see I commented out some unused functions at the end of the patch. I did this because I'm playing with a calendar plugin which also uses sabre dav, but evidently an other version. Is there some way to cleanly contain the sabre dav libs from each other?

**Comment by blind-coder** [comment] 2016-01-20 11:31
I'll look into that patch soon, thanks in advance for it!

If you mean the Kolab calendar plugin, I've not yet managed to run them together but I've also not looked into it very much, to be honest.

**Comment by c-schwamborn** [comment] 2016-01-20 13:52
yes and no, the original Kolab plugin doesn't support caldav sources, 
it's only for calendars on kolab servers, but there is a project at:
https://gitlab.awesome-it.de/groups/kolab
They implemented native caldav support into the kolab plugin and are 
currently trying to merge their code with the kolab master (at least if 
I understood correct). There are still some bugs (for example: you can't 
move events between calendars), but I got it to work (commenting out 
those lines in carddav's sabre dav libs).

**Comment by mstilkerich** [comment] 2020-07-19 18:14
The loops you changed work on multi-value attributes / the address attribute, all of which have subtypes in coltypes set. Thus I wonder how these warnings can occur. Did you change the coltypes definition?

I'm closing this ticket because it is years old, however, if the issue is still relevant to you, please try the v4 branch. If you have problems with that, comment / reopen the issue and I will help.

**Closed by mstilkerich** 2020-07-19 18:14 UTC
