### ISSUE TITLE
rcmcarddav and radicale?

### ISSUE THREAD

**Issue by ScrumpyJack** [blind-coder/rcmcarddav#280] opened 2020-01-06 16:10 UTC
Anyone got this working with Radicale?

I've tried both the latest release and a git clone.

I enter credentials and the carddav URL in the "Settings -> CardDAV" form like this

https://radicale-host/user/a123456a-8888-aa01-bb02-abcdef12345678/

My rcmcarddav config.inc.php file is default (no presets), so I don't expect the plugin to send the same credentials as %u and %p passed from roundcude, it should send the credentials from the carddav form, correct?

> [7676294b3b20] DEBUG: anonymous user has read and write access to collection user/a123456a-8888-aa01-bb02-abcdef12345678
> 
> [7676294b3b20] INFO: Access to user/a123456a-8888-aa01-bb02-abcdef12345678/ denied for anonymous user
> 
> [7676294b3b20] DEBUG: Asking client for authentication
> 
> [7676294b3b20] DEBUG: Response content: Access to the requested resource forbidden.
> 
> [7676294b3b20] INFO: PROPFIND response status for user/a123456a-8888-aa01-bb02-abcdef12345678/ with depth '0' in 0.013 seconds: 401 Unauthorized
> 

This works fine on rainloop (which I'm trying to move away from).

any ideas?

**Comment by oregszun** [comment] 2020-01-07 14:41
After a day of searching I found that the problem is that the plugin can not determine the http auth scheme. 

The 401 will disappear after specifying the scheme manually. But the plugin itself still does not work, altought its getting 207 multi status from radicale.

 $scheme = strtolower($carddav['authentication_scheme']);
 **$scheme = "basic";**
 if ($scheme != "basic" && $scheme != "digest" && $scheme != "negotiate"){

**Comment by ScrumpyJack** [comment] 2020-01-09 14:57
This is a great find! Has it ever worked? Perhaps we can look at changes to see what might have broken with radicale?

**Comment by mstilkerich** [comment] 2020-07-12 14:48
This should be fixed on the v4 branch.

**Closed by mstilkerich** 2020-07-12 14:48 UTC
