### ISSUE TITLE
Creation of new records not working with DaViCal 1.1.0

### ISSUE THREAD

**Issue by imlich** [blind-coder/rcmcarddav#26] opened 2014-05-01 10:04 UTC
Hi,

I am running roundcube master, rcmcarddav master and davical 1.1.0.

Creation of a new record does throw out an error message ("An error occured", "An error occured while saving"). Subsequently the new address is not shown in roundcube carddav addressbok, but it is available on server (can download new record with other clients).

Have an perfectly running old version of roundcube and rcmcarddav with the same davical server, so I suspect it to be rather on client side.

Debug-Log: https://gist.github.com/imlich/3cf58b242f99b175f9ae

If needed can supply test-account on either the davical side or the roundcube side.

**Comment by tuxick** [comment] 2015-10-08 13:04
On my system i found log saying " Couldn't delete CardDAV-Contact from the local database with the vCard id", so no ID was passed at all. The card did get added!

I have no idea why it tries to delete a record when adding a new one, but my fix was in carddav_addressbook.php:

 
private function carddav_addressbook_delete($vcard_id)
  {    if ( '' == $vcard_id) {
      self::write_log('cowardly refusing to delete vcard without ID');
      return true;
    }

i believe this is just a hack, it shouldn't be called at all, especially not with empty vcard_id but at least i can now add cards without getting wrong error messages

**Comment by mstilkerich** [comment] 2020-07-14 10:32
I'm closing this issue because of it's age. Davical is tested and works with the current v4 development branch:
https://github.com/blind-coder/rcmcarddav/tree/v4

If the issue is still relevant to you, please comment / reopen on the issue.

**Closed by mstilkerich** 2020-07-14 10:32 UTC
