### ISSUE TITLE
Roundcube + Carddav not working

### ISSUE THREAD

**Issue by spravtek** [blind-coder/rcmcarddav#103] opened 2015-06-05 23:12 UTC
I keep getting db error when logging into Roundcube, when I look in the logs I see following error:
DB Error: [7] ERROR:  relation "carddav_addressbooks" does not exist
LINE 1: SELECT id FROM carddav_addressbooks WHERE user_id='1' AND ac...
                       ^ (GET /?_task=addressbook)

I'm using virtual users in Dovecot with a postgresql database, I used the postgres.sql script to create the tables, which after some tweaking kind of works (replaced users with virtual_users and (user_id) with (domain_id) ... But I guess something is still not quite right, can't seem to find it. Would appreciate some help! When I run the query SELECT * FROM carddav_addressbooks I get an empty table in return, so the table exists but a relation is missing??

**Comment by blind-coder** [comment] 2015-06-07 15:12
This is a duplicate of #96
You can work around it by manually applying the respective dbmigrations/0000-dbinit/ file on your roundcube database.

**Closed by blind-coder** 2015-06-07 15:12 UTC
