### ISSUE TITLE
Sabre\DAV\Exception\NotFound: Principal with name ...  not found -- possibly harmless

### ISSUE THREAD

**Issue by sphakka** [blind-coder/rcmcarddav#297] opened 2020-08-03 10:49 UTC
With my setup as in Issue #293, I see in `roundcube/carddav.log` a possibly harmless error:
```
[2020-Aug-03 12:05:08 +0200]: <5v3kvqo8> Errors occurred during the refresh of addressbook 11: Exception: Expected Multistatus HTTP request was not successful (404 Not Found): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Principal with name *** not found</s:message>
</d:error>
 in /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/CardDavClient.php:364
Stack trace:
#0 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/CardDavClient.php(379): MStilkerich\CardDavClient\CardDavClient::assertHttpStatus()
#1 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/CardDavClient.php(314): MStilkerich\CardDavClient\CardDavClient::checkAndParseXMLMultistatus()
#2 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/WebDavCollection.php(75): MStilkerich\CardDavClient\CardDavClient->findProperties()
#3 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/WebDavCollection.php(66): MStilkerich\CardDavClient\WebDavCollection->refreshProperties()
#4 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/WebDavCollection.php(137): MStilkerich\CardDavClient\WebDavCollection->getProperties()
#5 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/WebDavCollection.php(111): MStilkerich\CardDavClient\WebDavCollection->supportsReport()
#6 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/Services/Sync.php(96): MStilkerich\CardDavClient\WebDavCollection->supportsSyncCollection()
#7 /var/lib/roundcube/vendor/mstilkerich/carddavclient/src/Services/Sync.php(59): MStilkerich\CardDavClient\Services\Sync->synchronizeOneBatch()
#8 /var/lib/roundcube/plugins/carddav/src/Addressbook.php(334): MStilkerich\CardDavClient\Services\Sync->synchronize()
#9 /var/lib/roundcube/plugins/carddav/src/Addressbook.php(182): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->resync()
#10 /var/lib/roundcube/plugins/carddav/carddav.php(341): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->__construct()
#11 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(469): carddav->getAddressbook()
#12 /usr/share/roundcube/program/include/rcmail.php(226): rcube_plugin_api->exec_hook()
#13 /usr/share/roundcube/program/steps/addressbook/photo.inc(40): rcmail->get_address_book()
#14 /usr/share/roundcube/index.php(306): include_once('/usr/share/roun...')
#15 {main}
```
However, everything looks fine so far...

**Comment by mstilkerich** [comment] 2020-08-03 16:10
Well, unfortunately this means that the synchronization is aborted. The message "principal not found" that the server provides suggests that it does not know the user.

The request that fails is essentially issued on any communication with the server, so if it worked before (like discovery when adding the addressbook and previous syncs that apparently worked), I wonder what part of the environment changed.

I tried a bit and if I change the user name inside the URL to some user that does not exist I get exactly the same error. Can you check in carddav_http.log what URL the PROPFIND request is sent to, and whether it contains the proper URL? It should go to the URL of the addressbook.

**Comment by mstilkerich** [comment] 2020-08-17 04:22
Closing because of no reply within 2 weeks and because I'm not able to reproduce.

**Closed by mstilkerich** 2020-08-17 04:22 UTC
