### ISSUE TITLE
Roundcube Address book search isn't matching simple results with Carddav

### ISSUE THREAD

**Issue by nja0087** [blind-coder/rcmcarddav#190] opened 2017-03-30 09:09 UTC
Roundcube dev claims it's the plugin at fault: https://github.com/roundcube/roundcubemail/issues/5712

**Comment by blind-coder** [comment] 2017-03-30 10:08
Possible duplicate of #187 
Please check current dev-master if the issue still exists.

**Comment by mstilkerich** [comment] 2020-07-19 17:53
Closing for the lack of feedback. For me search appears to work fine, though the described issue sounds like it might be difficult to reproduce. If you still have this problem with the v4 development branch, feel free to comment / reopen.

**Closed by mstilkerich** 2020-07-19 17:53 UTC
