### ISSUE TITLE
Configuring NextCloud DAV server does nothing

### ISSUE THREAD

**Issue by asterismo** [blind-coder/rcmcarddav#178] opened 2017-01-07 05:42 UTC
I cannot get to set up NextCloud DAV contacts in carddav. The CardDav setting toogle appears in configuration but after setting all variables and DAV url and saving, everything resets to blanks and nothing happens. I tried installing plugin from GIT and composer and the same. I got this log from carddav:

[07-Jan-2017 04:07:18 +0000]: <fjha8vndt> In migration: 0000-dbinit
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> Found 6 matches
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> In migration: 0000-sample
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> Found 1 matches
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> In migration: 0001-categories
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> Found 1 matches
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> In migration: 0002-increasetextfieldlengths
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> Found 2 matches
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> In migration: 0003-fixtimestampdefaultvalue
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> Found 1 matches
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> In migration: 0004-fixtimestampdefaultvalue
[07-Jan-2017 04:07:18 +0000]: <fjh8vndt> Found 1 matches

error log shows nothing.

**Comment by asterismo** [comment] 2017-01-07 05:43
I'm using Debian 8 jessie and PHP 5.6.29-0+deb8u1

**Comment by blind-coder** [comment] 2017-01-07 06:55
Am 7. Januar 2017 06:43:06 MEZ schrieb Santiago Roland <notifications@github.com>:
>I'm using Debian 8 jessie and PHP 5.6.29-0+deb8u1
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/178#issuecomment-271064911

Which URL do you enter into the address field? If well known URLs are setup, then the addressbooks should be found automatically.

**Comment by asterismo** [comment] 2017-01-07 17:53
Following this information i issued this URL:
https://cloud.myserver.com/remote.php/dav/
Source: https://davdroid.bitfire.at/configuration/nextcloud/

**Comment by asterismo** [comment] 2017-01-07 18:21
I couldn't find any URL in NextCloud that said "paste me in your dav client..." whatsoever... it still quite obscure to me as an end user although the functionality is great.

**Comment by dnel** [comment] 2017-01-12 10:45
I had this same issue but the well-knowns are configured on my server so I just entered the server address and this worked, after that the url appeared in this format:

https://<server>:443/remote.php/carddav/addressbooks/<user>/contacts/

**Comment by blind-coder** [comment] 2017-01-21 12:03
I'll have to set up a nextcloud server and try this, but it sounds like a server error to me.

**Comment by blind-coder** [comment] 2017-01-21 12:25
It just worked fine for me, but I had to prepend the http:// for it to work. Can you please check if it works for you then? If so, it's probably an issue of prepending that if it's missing...

**Comment by asterismo** [comment] 2017-01-23 04:58
I tried this https://[server]:443/remote.php/carddav/addressbooks/[user]/contacts/ and it did not worked, i have the contacts app enabled in NextCloud, and i can sync them using DAVContacts in Android. No luck with this.

**Comment by blind-coder** [comment] 2017-01-23 08:50
@asterismo That is weird... Can you please set the variables DEBUG and DEBUG_HTTP in carddav_common.php to true and then check roundcube/logs/carddav for any information? It wil log the complete HTTP requests into there (including passwords, be careful when posting them).

**Comment by asterismo** [comment] 2017-01-23 17:14
It does not log anything useful... and it is from days ago...

[07-Jan-2017 04:07:18 +0000]: <fga8vndt> In migration: 0000-dbinit
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> Found 6 matches
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> In migration: 0000-sample
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> Found 1 matches
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> In migration: 0001-categories
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> Found 1 matches
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> In migration: 0002-increasetextfieldlengths
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> Found 2 matches
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> In migration: 0003-fixtimestampdefaultvalue
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> Found 1 matches
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> In migration: 0004-fixtimestampdefaultvalue
[07-Jan-2017 04:07:18 +0000]: <fga8vndt> Found 1 matches

**Comment by blind-coder** [comment] 2017-01-23 18:30
that's weird... after enabling those variables and adding an addressbook, there's NOTHING on the logs?

**Comment by asterismo** [comment] 2017-01-23 18:37
nope

**Comment by blind-coder** [comment] 2017-01-23 18:48
That is very strange. The only case in which NOTHING would be printed is if the URL you enter doesn't match this regex:
`preg_match(';^(([^:]+)://)?(([^/:]+)(:([0-9]+))?)(/?.*)$;')`
or... wait..

Did you enter a NAME for the addressbook when adding? It won't do anything if you don't.

**Comment by asterismo** [comment] 2017-01-23 21:43
What NAME it is? Is it some name of the NextCloud addressbook? or just a name for Roundcube to identify it?

**Comment by asterismo** [comment] 2017-01-23 21:46
In NextCloud i have contacts under "All Contacts" in the left sidebar, not sure if this helps

**Comment by blind-coder** [comment] 2017-01-25 08:01
The name is just a name for roundcube to display in the addressbooks tab, it has no function other than to help you identify which addressbook you are working with right now.

**Comment by asterismo** [comment] 2017-01-25 08:23
Yes, i put some name, its the same, it does nothing...

**Comment by jschreuder** [comment] 2017-01-27 02:18
Got the same problem using PHP7 on Ubuntu 16.04. It reports success in the bottom right corner with a green success message, but nothing else happens and the form returns empty. I've checked in the database and the settings don't seem to have been stored.

Though I'm working with RC 1.3-beta and dev-master for this plugin. I switched from ^2.0 in composer to dev-master which did solve the incompatible method definition warnings. But nothing else regretably, can't find any error anywhere. My logs look the same as asterismo's.

**Comment by freibadschwimmer** [comment] 2017-03-29 17:31
I stumbled over the same problem with RC 1.3 beta, with the same error message as in the first post.
Following the previous advise I also downgraded to 1.2 and carddav worked as expected.
I don't know why that happened, but I saw one difference during installation. I use composer to install plugins:
In 1.3 after adding carddav to the composer.json it only installs carddav.
In 1.2. it furthermore pulls sabre/vobject and nategood/httpful.

So my conclusion is that when using composer with the current 1.3 beta not all dependencies are being pulled.

**Comment by blind-coder** [comment] 2017-03-30 07:37
I can't quite reproduce it here, having only carddav in my composer.json, it pulls vobject and httpful just fine.
Can you please post your composer.json file and the output from composer.phar update?

**Comment by freibadschwimmer** [comment] 2017-03-30 12:57
Thanks for looking into this!
I already deleted the RC folder in which I had the problems yesterday.

I just tried again to install carddav on a fresh install of 1.3-beta and I could not reproduce the issue either, so the installation with the "dev-master" worked on a fresh 1.3-beta today.
Maybe there was a mistake (or a conflict, as I had quite some plugins in the list) in the configuration.

Yet, I experienced the same messages as described in the first post, so maybe it helps to check whether these dependencies have been installed.

**Comment by arnowelzel** [comment] 2017-09-12 12:37
JFTR: I have similar problems with Ubuntu 16.04, PHP 7.0, MariaDB 10, RoundCube 1.3.1 and RCMCardDAV v2.0.4.

I did a fresh installation of everything with a new database and I still can't add any CardDAV addressbook. RoundCube itself works without any problems.

**Comment by dvzrv** [comment] 2017-09-13 17:32
Same problem on Arch, mariadb 10.1.26, php 7.1.9, roundcubemail 1.3.1, rcmcarddav 2.0.4 using nextcloud 12.0.2. Unable to add address books from a local nextcloud dav instance.

roundcube's sql and error logs show:

```
==> sql <==
[13-Sep-2017 19:29:53 +0200]: <osdpep0j> [3] SELECT id FROM carddav_addressbooks WHERE user_id='1' AND active=1;
[13-Sep-2017 19:30:53 +0200]: <osdpep0j> [1] SELECT `vars`, `ip`, `changed`, now() AS ts FROM `session` WHERE `sess_id` = 'osdpep0j48qtisqae0gea7mpf1';
[13-Sep-2017 19:30:53 +0200]: <osdpep0j> [2] SELECT * FROM `users` WHERE `user_id` = '1';

==> errors <==
[13-Sep-2017 19:30:53 Europe/Berlin] PHP Warning:  Declaration of carddav_backend::delete($ids) should be compatible with rcube_addressbook::delete($ids, $force = true) in /usr/share/webapps/roundcubemail/plugins/carddav/carddav_backend.php on line 26
[13-Sep-2017 19:30:53 Europe/Berlin] PHP Warning:  Declaration of carddav_backend::list_groups($search = NULL) should be compatible with rcube_addressbook::list_groups($search = NULL, $mode = 0) in /usr/share/webapps/roundcubemail/plugins/carddav/carddav_backend.php on line 26
[13-Sep-2017 19:30:53 Europe/Berlin] PHP Warning:  Declaration of carddav_backend::rename_group($group_id, $newname) should be compatible with rcube_addressbook::rename_group($group_id, $newname, &$newid) in /usr/share/webapps/roundcubemail/plugins/carddav/carddav_backend.php on line 26

```

**Comment by jamfx** [comment] 2017-11-27 07:40
Is this Case still open, becaus I have the same problem right now with my NextCloud 12.0.3 and the latest RoundCube Release. Is there any solution to this?

**Comment by blind-coder** [comment] 2017-12-05 07:14
Please update to RoundCube 1.3.3 and NextCloud 12.0.4. I just tested this combination and it detected my addressbooks just fine.
Make sure that your /.well-known/carddav path in NextCloud works. If that returns a 404 error, your webserver is not configured correctly.

**Comment by jamfx** [comment] 2017-12-14 21:14
Sorry for the delay, I tried to do it with latest RoundCube 1.3.3 and latest NextCloud 12.0.4. I downloaded the ZIP from Github and still have the same Problem. Clears all fields, says "everything saved", but no Adressbook. :(

**Comment by blind-coder** [comment] 2017-12-15 06:43
Am 14. Dezember 2017 22:14:25 MEZ schrieb JamFX <notifications@github.com>:
>Sorry for the delay, I tried to do it with latest RoundCube 1.3.3 and
>latest NextCloud 12.0.4. I downloaded the ZIP from Github and still
>have the same Problem. Clears all fields, says "everything saved", but
>no Adressbook. :(
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/178#issuecomment-351837731

Please use a git clone of the master branch, not a release. They're ancient and broken.

**Comment by shaneonabike** [comment] 2017-12-15 15:17
Well I believe that master is also broken since my issue was with that version. Do you have any insight @blind-coder

**Comment by blind-coder** [comment] 2017-12-17 13:59
@shaneonabike 
Can you enable DEBUG and DEBUG_HTTP in carddav_backend.php and connect your NextCloud addressbook, then upload roundcube/logs/carddav? Make sure to prune passwords in there before that as it's showing the raw HTTP requests, including the Authorization header. I may be able to discern something from that, but as mentioned before, it works fine here so I assume a misconfiguration of NextCloud, Roundcube or your domains _carddav._tcp and _carddavs._tcp records.

**Comment by osos** [comment] 2017-12-25 20:27
On my setup it seems a couple of columns are missing int carddav_addressbook.

Deleting carddav tables from database and manually importing .sql files (automated didn't work) solved the issue.

**Comment by blind-coder** [comment] 2017-12-25 21:10
What happened during the automated process?
Did you logout, enable the plugin and login correctly?

**Comment by devurandom** [comment] 2018-03-20 07:09
@blind-coder Could you cut another release, if the latest is known to be "ancient and broken"?

**Comment by blind-coder** [comment] 2018-03-20 07:12
I could, but with dozens of open issues and little time to work on them, I don't feel comfortable doing that. Not sure if it'll improve or deteriorate the situation as it is.

**Comment by mstilkerich** [comment] 2020-07-17 05:05
Nextcloud works fine with v4 branch. If you are having issues with it, please comment / reopen.

**Closed by mstilkerich** 2020-07-17 05:05 UTC
