### ISSUE TITLE
Table 'roundcubemail.carddav_addressbooks' doesn't exist (GET /) doesn't exist

### ISSUE THREAD

**Issue by Happyfeet01** [blind-coder/rcmcarddav#189] opened 2017-03-16 16:28 UTC
Hello i try to install carddav for Roundcube. But i get this error below. 
i use the Plesk Version and this is installed in /usr/share/psa-roundcube/

i´m logged out from roundcube and start to install.
Roundcube Version is 1.2.2 and i use the carddav Master Version.

```
[16-Mar-2017 17:22:17 +0100]: <ua413d6r> DB Error: [1146] Table 'roundcubemail.c                                                                                                                                                             arddav_addressbooks' doesn't exist (SQL Query: SELECT id,password FROM carddav_a                                                                                                                                                             ddressbooks WHERE user_id='4') in /usr/share/psa-roundcube/program/lib/Roundcube                                                                                                                                                             /rcube_db.php on line 539 (POST /?_task=login&_action=login)
[16-Mar-2017 17:22:17 +0100]: <ua413d6r> DB Error: [1146] Table 'roundcubemail.c                                                                                                                                                             arddav_addressbooks' doesn't exist (SQL Query: SELECT * FROM carddav_addressbook                                                                                                                                                             s WHERE user_id='4' AND presetname is not null) in /usr/share/psa-roundcube/prog                                                                                                                                                             ram/lib/Roundcube/rcube_db.php on line 539 (POST /?_task=login&_action=login)
[16-Mar-2017 17:22:18 +0100]: <ua413d6r> DB Error: [1146] Table 'roundcubemail.c                                                                                                                                                             arddav_addressbooks' doesn't exist (SQL Query: SELECT id FROM carddav_addressboo                                                                                                                                                             ks WHERE user_id='4' AND active=1) in /usr/share/psa-roundcube/program/lib/Round                                                                                                                                                             cube/rcube_db.php on line 539 (GET /?_task=mail&_token=cn32DBqm6e7GezrgyIXZrFIHV                                                                                                                                                             ZQhruun)
[16-Mar-2017 17:22:18 +0100]: <ua413d6r> DB Error: [1146] Table 'roundcubemail.c                                                                                                                                                             arddav_addressbooks' doesn't exist (GET /?_task=mail&_token=cn32DBqm6e7GezrgyIXZ                                                                                                                                                             rFIHVZQhruun)
```

Maybe the composer stopped?

```
Key require is a duplicate in ./composer.json at line 35
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

**Comment by blind-coder** [comment] 2017-04-25 10:11
I don't know the plesk version. You should contact the maintainer of that.

**Comment by Proton23** [comment] 2018-03-26 19:40
I'm curios if there is a solution because I have the exact same problem..
also I don't understand why this is a plesk issue and why roundcube on plesk is different...
Maybe somebody can explain it :smirk:

**Comment by evlist** [comment] 2020-03-24 16:17
I have the same issue with the standard (non plesk) version and I have noticed that, in carddav.php, the code that tests if this table exists to create it at installation time has been commented out:

```php
                # first initialize the carddav_migrations table if it doesn't exist.
                /*
                $query = file_get_contents(dirname(__FILE__)."/dbinit/".$db_backend.".sql");
                if (strlen($query) > 0){
                        $query = str_replace("TABLE_PREFIX", $config->get('db_prefix', ""), $query);
                        $dbh->query($query);
                        rcmail::write_log("carddav", "Processed initialization of carddav_migrations table");
                } else {
                        rcmail::write_log("carddav", "Can't find migration: /dbinit/".$db_backend.".sql");
                }
                */
```
Un-commenting this block fixes the problem and I wonder why these comments may have been added !

**Comment by mstilkerich** [comment] 2020-07-06 16:35
It is commented out because it is no longer needed. The database is initialized by playing through all the DB migrations. The query for the existing DB migrations ignores the error if the table does not exist. See a couple of lines below the code you quoted:

```
$dbh->set_option('ignore_key_errors', true);
		$sql_result = $dbh->query('SELECT * FROM '.
			$dbh->table_name('carddav_migrations') .
			' WHERE filename IN ('.$qmarks.');', $migrations);

		if ($sql_result){
			while ($processed = $dbh->fetch_assoc($sql_result)) {
				if(($key = array_search($processed['filename'], $migrations)) !== false) {
							unset($migrations[$key]);
				}
			}
		}
		$dbh->set_option('ignore_key_errors', null);
```

For me, the code works. You will get the error message on first login, but then the database should be initialized.

**Comment by mstilkerich** [comment] 2020-07-18 09:06
I'm closing this as there is no reply and I cannot reproduce that issue. If the issue persists for you, feel free to comment/reopen.

**Closed by mstilkerich** 2020-07-18 09:06 UTC
