### ISSUE TITLE
Can't add new contact on a Nextcloud addressbook

### ISSUE THREAD

**Issue by sphakka** [blind-coder/rcmcarddav#293] opened 2020-06-12 10:09 UTC
With Roundcube-1.4.5, carddav-3.0.3 and Nextclud-18.0.6 on Debian 10.
I can modify existing contacts but cannot create new ones in a Nextcloud addressbook. GUI says

    An error occurred while saving

while `carddav.warn.log` says:
```
BACKEND: (get_record_from_carddav) Request for VCF '11C11016-9EEF-4105-A6F5-8317753A3885.vcf' which doesn't exist on the server.
```
No message logged in other carddav logs nor on NC side. 
Carddav conf is:
```
$prefs['Nextcloud'] = array(
	'name'         =>  'Personal -- nextcloud',
	'username'     =>  '%u',
	'password'     =>  '%p',
	'url'          =>  'https://OBFUSCATED/remote.php/dav/addressbooks/users/%u/Contacts/',
	'active'       =>  true,
	'readonly'     =>  false,
	'refresh_time' => '00:30:00',
	'fixed'        =>  array(
		'name',
		'username',
		'password',
		'url',
	 ),
	'hide'         =>  false,
	'use_categories' => true,
);

```

**Comment by mstilkerich** [comment] 2020-06-28 16:34
Hello,

you can try the version 4 development branch, which should work with Nextcloud 18.

See installation instructions here: https://github.com/blind-coder/rcmcarddav/tree/v4

**Comment by sphakka** [comment] 2020-06-28 19:17
Hi, thanks for the tip. 

Yeah, there something really fishy: yesterday, after a PHP upgrade from 7.3 to 7.4. clean-up, reboot, etc., the bug didn't manifest. But now I see it coming again, and at the same time the synchronization is failing for all books, with errors like:

    BACKEND: (refreshdb_from_server) Errors occurred during the refresh of addressbook 16

Maybe something related to stale sessions / tokens?

**Comment by mstilkerich** [comment] 2020-06-28 19:28
Are these errors occuring on the v4 branch? If so, could you please enable debugging in config.inc.php (see config.inc.php.dist for the relevant parameters, set both loglevels to DEBUG) and provide the logfiles? Be sure to strip confidential info (especially Authorization headers in the http log) from the logfiles.

**Comment by texxasrulez** [comment] 2020-07-15 04:36
To chime in, I installed v4 branch just a bit ago and I use Nextcloud exclusively. I must say v4 works flawlessly for me. I must also add that I have used this plugin without issue for years since NC's first release up to and including v18. I can add, edit, delete, pretty much everything I have ever tried without fail.

**Comment by sphakka** [comment] 2020-07-17 13:23
Just installed v4 on my Debian 4x with composer. But I get:
```
[17-Jul-2020 15:10:06 Europe/Zurich] PHP Fatal error:  Uncaught Error: Class 'MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger' not found in /usr/share/roundcube/plugins/carddav.4x/carddav.php:74
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(100): carddav->init()
#1 /usr/share/roundcube/program/include/rcmail.php(137): rcube_plugin_api->init()
#2 /usr/share/roundcube/program/include/rcmail.php(78): rcmail->startup()
#3 /usr/share/roundcube/index.php(43): rcmail::get_instance()
#4 {main}
  thrown in /usr/share/roundcube/plugins/carddav.4x/carddav.php on line 74
```
Similar to Issue #286

**Comment by mstilkerich** [comment] 2020-07-17 13:25
Did you run composer in the root directory of roundcube,  not in the plugin directory? See installation instructions of the README

**Comment by sphakka** [comment] 2020-07-17 14:02
Sure, files are all there. Never mind the path  `carddav.4x` (I had a symlink); I reinstalled it again and it's the same.
```
...
thrown in /usr/share/roundcube/plugins/carddav/carddav.php on line 74
```
Forgot to say, I used composer shipped by Debian:
```
$ composer -V
Composer 1.10.8 2020-06-24 21:23:30
```
Would it be possible to have a beta release tarball to drop in directly? Debian's folks might also be up to take it for proper packaging in [Bullseye ](roundcube-plugins-extra).

**Comment by mstilkerich** [comment] 2020-07-17 14:56
v4 expects its classes to be loaded by composer's autoloader, which is normally shipped with roundcube and loaded by roundcube. It should be located in roundcube/vendor/autoload.php.

The debian package has the roundcube package split into /var/lib/roundcube and /usr/share/roundcube. Roundcube's INSTALL_PATH is set to /var/lib/roundcube, so roundcube would look for /var/lib/roundcube/vendor/autoload.php and you should install the carddav plugin there, too (at least the vendor directory needs to be there). Then they have put composer.json to /usr/share/roundcube, but if you run composer there the dependencies won't be found.  So you'd have to copy/link that over to /var/lib/roundcube first. Finally, they have patched package names in composer.json (pear -> pear-pear.php.net, net_socket -> net-socket), which causes composer to not find these packages in the standard repositories. I have no clue why they did that, but you have to name them back for composer to work.

So to summarize to make it work with the debian package (I tried this on Ubuntu 18.04, but AFAIK they take the packages from debian):
1. copy over /usr/share/roundcube/composer.json to /var/lib/roundcube/composer.json
2. edit composer.json: change back all pear-pear.php.net/ to pear/, change net-socket to net_socket
3. edit composer.json: add "roundcube/carddav": "v4.x-dev" to the require array
4. run composer update --no-dev in /var/lib/roundcube
5. add 'carddav' to the list of plugins (you already did that)

A tarball installation is not currently supported, and I'd like to drop support for it. The reason is that with that approach, I have to include the dependencies in the tarball / plugin directory (or who would take care of installing them to roundcube/vendor?), and the same php modules may be installed with conflicting version in roundcube / other roundcube plugins. We had several issue reports here caused by this. With dependencies managed for the entire roundcube location, composer can do its job and resolve these constraints to choose compatible dependencies or print an error in case this is not possible.

**Comment by mstilkerich** [comment] 2020-07-21 19:56
@sphakka: I did an alpha release including a tarball if you want to try:
https://github.com/blind-coder/rcmcarddav/releases/

**Comment by sphakka** [comment] 2020-07-28 13:46
Thanks for the explanation of Debian's installation and how to work it around: your recipe did the trick ^^ 
(I also tried the tgz but got the same error -- I guess it's a dead end...) 

I'll send an RFE for inclusion in Debian's `roundcube-plugins[-extra]`.

You can close this issue.

**Comment by mstilkerich** [comment] 2020-07-28 14:01
Well the tarball should work if you follow the instructions for tarball installation at https://github.com/blind-coder/rcmcarddav/blob/master/doc/INSTALL.md

You still need to run composer to install the dependencies, they are not in the tarball.

Btw, the v4 branch has now been merged to master and the branch is not updated anymore.

**Closed by mstilkerich** 2020-07-28 14:01 UTC

**Comment by sphakka** [comment] 2020-08-03 15:44
Thanks for the help. Unfortunately the mix-up of Debian packages with carddav (+ deps) installed via composer screwed Debian's upgrade of Roundcube: possible culprit is the modified `composer.json` file. Finally, I had to remove carddav and reinstall Roundcube... too bad!

BTW, here's the RFE for inclusion in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966494

**Comment by mstilkerich** [comment] 2020-08-03 15:58
If you follow the instructions for tarball installations, the dependencies are installed inside the plugins/carddav folder and nothing outside that folder belonging to the debian package needs to be modified. It has drawbacks with respect to conflicting versions of the dependencies which I have outlined above.

You could also put a plugin checked out from git in the plugins/carddav folder and do the same as with the tarball to install dependencies inside the plugin folder, with the same caveats.

Unfortunately, this is all I can do if you want to use the plugin with the packaged version of roundcube.
