### ISSUE TITLE
"PHP Deprecated carddav/carddav.php on line 352" with roundcube-1.4.4

### ISSUE THREAD

**Issue by Thom1b** [blind-coder/rcmcarddav#289] opened 2020-05-01 05:37 UTC
Hi,

Since I upgrade from roundcube 1.4.3 to 1.4.4, the script "./bin/clean.sh" show this deprecated message : 
`PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/roundcubemail/plugins/carddav/carddav.php on line 352`

I use php-7.4.5. I think carddav code needs to be updated.

Thanks, have a nice day!

**Comment by mstilkerich** [comment] 2020-07-12 14:51
Duplicate of #277

**Closed by mstilkerich** 2020-07-12 14:51 UTC
